services:
  backend:
    build: backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://perfectly_planned:perfectly_planned_password@db:5432/perfectly_planned
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=perfectly_planned
      - POSTGRES_PASSWORD=perfectly_planned_password
      - POSTGRES_DB=perfectly_planned
  frontend:
    build: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
# Volumes for persisting data, see https://docs.docker.com/engine/reference/builder/#volume
volumes:
  postgres_data:
