services:
  backend:
    build: backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://perfectly_planned:perfectly_planned_password@db:5432/perfectly_planned
      GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
      GOOGLE_URL: ${GOOGLE_URL}
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=perfectly_planned
      - POSTGRES_PASSWORD=perfectly_planned_password
      - POSTGRES_DB=perfectly_planned
  frontend:
    build: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
      VITE_API_URL: ${VITE_API_URL}
      VITE_GOOGLE_AUTH_DOMAIN: ${VITE_GOOGLE_AUTH_DOMAIN}
      VITE_GOOGLE_AUTH_PROJECT_ID: ${VITE_GOOGLE_AUTH_PROJECT_ID}
      VITE_GOOGLE_AUTH_STORAGE_BUCKET: ${VITE_GOOGLE_AUTH_STORAGE_BUCKET}
      VITE_GOOGLE_AUTH_MESSAGING_SENDER_ID: ${VITE_GOOGLE_AUTH_MESSAGING_SENDER_ID}
      VITE_GOOGLE_AUTH_APP_ID: ${VITE_GOOGLE_AUTH_APP_ID}
      VITE_GOOGLE_AUTH_MEASUREMENT_ID: ${VITE_GOOGLE_AUTH_MEASUREMENT_ID}
  # Volumes for persisting data, see https://docs.docker.com/engine/reference/builder/#volume
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    ports:
      - "5672:5672"
volumes:
  postgres_data:
