"""Test

Revision ID: b3ce6507aca1
Revises: 
Create Date: 2023-07-28 13:56:43.990443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b3ce6507aca1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weddings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weddings',
    sa.Column('wedding_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wedding_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('wedding_theme', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wedding_budget', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wedding_guest', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wedding_venue', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wedding_decorations', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wedding_registry', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wedding_planner', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('wedding_photographer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('wedding_id', name='weddings_pkey')
    )
    # ### end Alembic commands ###
