"""Test

Revision ID: 20006b7186d1
Revises:
Create Date: 2023-07-24 19:12:33.438650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20006b7186d1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "todos",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("text", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("completed", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="todos_pkey"),
    )


# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("todos")


# ### end Alembic commands ###
